server:
  port: 8081
  
  
okta:
  oauth2:
    issuer: https://dev-75940483.okta.com/oauth2/default
    audience: api://default
    
spring:
  application:
    name: user-service
    
  datasource:
    name: userdb
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: darshan@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  

  config:
    import: configserver:http://localhost:8989
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-75940483.okta.com/oauth2/default
      client:
        registration:
          internalClient:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa8kdm6knLmFWTTj5d7
            client-secret: DoSFZ614s5XlqHiJvnmPIQ3nMZuoYi-rpaa54Afv
        provider:
          okta:
            issuer-uri: https://dev-75940483.okta.com/oauth2/default

#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka]

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  
  endpoint:
    health:
      show-details: always
      
resilience4j:
  circuitbreaker:
    instances:
      userCircuitBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
  retry:
    instances:
      userRetry:
        max-attempts: 3
        wait-duration: 5s
  
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s
        
        